
apiVersion: apps/v1
kind: Deployment
metadata:
  name: seid-deployment-blue-v1
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: seid-java
      version: v1
  template:
    metadata:
      labels:
        app: seid-java
        version: v1
    spec:
      containers:
        - name: seid-java
          image: seidpeace/seid-java:v1
          ports:
            - containerPort: 8090
              protocol: TCP
          imagePullPolicy: Always
          env:
          - name: GREETING_SEID
            valueFrom:
              configMapKeyRef:
                name: spring-config
                key: hello.greeting
          - name: ENVIRONMENT_CONFIG_SEID
            valueFrom:
              configMapKeyRef:
                name: spring-config
                key: ENVIRONMENT_CONFIG
          - name: SECRETS_DEMO_USER
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: spring.user.name
          - name: SECRETS_DEMO_USER_PASSWD
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: spring.user.password
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8090
            initialDelaySeconds: 50
            periodSeconds: 50          
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8090
            initialDelaySeconds: 50
            periodSeconds: 50   

