---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: seid-k8s-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: seid-java
  template:
    metadata:
      labels:
        app: seid-java
    spec:
      containers:
        - name: seid-java
          image: seidpeace/seid-java:v1
          ports:
            - containerPort: 8090
              protocol: TCP
          imagePullPolicy: Always
          env:
          - name: GREETING_SEID
            valueFrom:
              configMapKeyRef:
                name: spring-config
                key: hello.greeting
          - name: ENVIRONMENT_CONFIG_SEID
            valueFrom:
              configMapKeyRef:
                name: spring-config
                key: ENVIRONMENT_CONFIG
          - name: SECRETS_DEMO_USER
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: spring.user.name
          - name: SECRETS_DEMO_USER_PASSWD
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: spring.user.password
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8090
            initialDelaySeconds: 50
            periodSeconds: 50          
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8090
            initialDelaySeconds: 50
            periodSeconds: 50   
---
apiVersion: v1
kind: Service
metadata:
  name: seid-java
spec:
  selector:
    app: seid-java
  ports:
    - nodePort: 30163
      port: 80
      targetPort: 8090
  type: NodePort

