server:
    port: 8090
    
management:
  endpoints:
    web:
      exposure:
        include: info, health,beans
    #enabled-by-default: false
      group:
        liveness:
          include: "livenessStateProbeIndicator"
        readiness:
          include: "readinessStateProbeIndicator"
 
      
          
          
app:
  config: Default value
  environmentVariable: ${ENVIRONMENT_CONFIG_SEID:Default value}
  
 
hello:
  greeting: ${GREETING_SEID:seidabdu}
  
user:
  name: ${SECRETS_DEMO_USER:demo}
  password: ${SECRETS_DEMO_USER_PASSWD:demo}

spring:
  output:
    ansi:
      enabled: ALWAYS
